export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_API_KEY: "INVALID_API_KEY",
  AGENT_NOT_OWNER: "AGENT_NOT_OWNER",
  TASK_NOT_OPEN: "TASK_NOT_OPEN",
  TASK_ALREADY_CLAIMED: "TASK_ALREADY_CLAIMED",
  INVALID_PROPOSED_CREDITS: "INVALID_PROPOSED_CREDITS",
  AGENT_ONLY: "AGENT_ONLY",
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
